export const glossary = [
  {
    term: 'dtc',
    title: 'Diagnostic Trouble Code (DTC)',
    seoTitle: 'What is a Diagnostic Trouble Code (DTC) in Chiptuning?',
    description: 'A Diagnostic Trouble Code (DTC) is a code generated by a vehicles On-Board Diagnostics (OBD) system when a malfunction is detected.',
    content: 'When tuning an ECU, you might need to remove specific DTCs to prevent warning lights (Check Engine Light) from appearing on the dashboard. TunerPortal offers integrated DTC removal API services.'
  },
  {
    term: 'cvn',
    title: 'Calibration Verification Number (CVN)',
    seoTitle: 'CVN Patch in ECU Tuning Explained',
    description: 'The Calibration Verification Number (CVN) is a checksum used by dealerships to verify if an ECU has been modified.',
    content: 'TunerPortal offers an automated CVN Patch API that corrects the CVN after tuning, ensuring the modification remains undetected during routine dealership diagnostic checks.'
  },
  {
    term: 'ecu',
    title: 'Engine Control Unit (ECU)',
    seoTitle: 'What is an Engine Control Unit (ECU)?',
    description: 'An Engine Control Unit (ECU) is a small computer inside a vehicle that controls various engine functions such as fuel mixture, ignition timing, and idle speed.',
    content: 'Chiptuning involves reading the software from the ECU, modifying the maps to increase performance or fuel efficiency, and writing the software back to the ECU. TunerPortal automates the management and processing of these ECU files.'
  },
  {
    term: 'winols',
    title: 'WinOLS',
    seoTitle: 'What is WinOLS and how is it used in tuning?',
    description: 'WinOLS is a dedicated software developed by EVC for modifying the memory contents of ECUs.',
    content: 'It is the industry standard for manual map editing. TunerPortal integrates seamlessly with WinOLS via LuaBot to fully automate your file service.'
  }
];
